const data={
    products:[
        {
            name:'Free Shirt',
            category:'shirt',
            image:'/images/shirt1.jpg',
            price:70,
            brand:'Nike',
            reating:4.5,
            numReviews:10,
            countInStock:20,
            description:'A popular shirt',
        },
        {
            name:'Free Shirt',
            category:'shirt',
            image:'/images/shirt2.jpg',
            price:70,
            brand:'Nike',
            reating:4.5,
            numReviews:10,
            countInStock:20,
            description:'A popular shirt',
        },
        {
            name:'Free Shirt',
            category:'shirt',
            image:'/images/shirt3.jpg',
            price:70,
            brand:'Nike',
            reating:4.5,
            numReviews:10,
            countInStock:20,
            description:'A popular shirt',
        },
        {
            name:'Free Shirt',
            category:'shirt',
            image:'/images/shirt1.jpg',
            price:70,
            brand:'Nike',
            reating:4.5,
            numReviews:10,
            countInStock:20,
            description:'A popular shirt',
        },
        {
            name:'Free Shirt',
            category:'shirt',
            image:'/images/shirt1.jpg',
            price:70,
            brand:'Nike',
            reating:4.5,
            numReviews:10,
            countInStock:20,
            description:'A popular shirt',
        },
    ]
}
export default data;