import Head from 'next/head'
import * as React from 'react';
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Grid } from '@mui/material';
import axios from 'axios'
import styles from '@/styles/Home.module.css'
import Navbar from './component/Navbar'
import Footer from './component/Footer'
import ActionAreaCard from './component/ActionAreaCard'

import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { CardActionArea, CardActions, Button } from '@mui/material';
import NextLink from 'next/link';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [productDetails, setProductDetails] = React.useState("");
  React.useEffect(() => {
    const url = "http://localhost:3000/api/products";
    async function fetchData() {
      try {
        const data = await axios.get(url);
        setProductDetails(data.data);

      } catch (error) {
        console.log(error);
      }
    }
    fetchData();

  }, [])
  console.log(productDetails);
  
  return (
    <>
      <Head>
        <title>Bazaar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar HeadingName="Bazaar" />
        <div>
          <h1>Products</h1>
          <Grid container spacing={3}>
            {productDetails ? productDetails.map((product) => (
              <Grid item md={4} key={product.id ? product.id : "01"}>
                <Card>
                  <NextLink href={`/product/${product.slug}`} passHref>
                    <CardActionArea>
                      <CardMedia
                        component="img"
                        image={product.image ? product.image : "/images/shirt1.jpg"}
                        title={product.name ? product.name : "t-shirt"}
                      ></CardMedia>
                      <CardContent>
                        <Typography>{product.name ? product.name : "t-shirt"}</Typography>
                      </CardContent>
                    </CardActionArea>
                  </NextLink>
                  <CardActions>
                    <Typography>${product.price ? product.price : "20"}</Typography>
                    <Button size="small" color="primary">
                      Add to cart
                    </Button>
                  </CardActions>
                </Card>
              </Grid>
            )) : ""}
          </Grid>


        </div>
        <footer>
          <Footer />
        </footer>
      </main >

    </>
  )
}
